#ifndef SNAKE_CONST_H

#define SNAKE_MAX_LENGTH 100
#define SNAKE_START_POS_X 10
#define SNAKE_START_POS_Y 6
#define SNAKE_START_LENGTH 2
#define SNAKE_TAIL_SYM '+'
#define SNAKE_SPEED 6

#define SNAKE_CONST_H
#endif
